apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dp
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app-pod
        image: 134986800938.dkr.ecr.us-east-1.amazonaws.com/project-ecr:app-v1
        ports:
        - containerPort: 81
        env:
          - name: DBPORT
            value: "3306"
          - name: DBUSER
            value: "root"
          - name: DATABASE
            value: "employees"
          - name: DBPWD
            value: "wordpass"
          - name: APP_COLOR
            value: "blue"
          - name: DBHOST
            value: "db-service"
          - name: BACKGROUND_IMAGE_URL
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: BACKGROUND_IMAGE_URL
        # envFrom:
        # - secretRef:
        #   name: app-secret

      imagePullSecrets:
      - name: regcred
