apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dp
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: app-pod
        image: 134986800938.dkr.ecr.us-east-1.amazonaws.com/project-ecr:app-v1
        ports:
        - containerPort: 81
        env:
          - name: BACKGROUND_IMAGE_URL
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: BACKGROUND_IMAGE_URL
          - name: DBPORT
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: DBPORT
          - name: DBHOST
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: DBHOST
          - name: DATABASE
            valueFrom:
              configMapKeyRef:
                name: proj-configmap
                key: DATABASE
          - name: DBUSER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBUSER
          - name: DBPWD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: DBPWD
      imagePullSecrets:
      - name: regcred
